### ISSUE TITLE
does not get content of node_modules package but it adds the my project index.js 

### ISSUE THREAD

**Issue by zymr-keshav** [cosminlupu/npmfiles#1]
I am using this package with below gulp task 

```

var npmVendors = gulp.src(mainNPMFiles( {nodeModulesPath: '../node_modules/'} ));

  var npmOptions = {
    relative: true,
    starttag: '<!-- inject:npm -->',
    ignorePath: [conf.paths.src, path.join(conf.paths.tmp, '/serve')],
    addRootSlash: false
  };

  return gulp.src(path.join(conf.paths.src, '/*.html'))
    .pipe($.inject(injectStyles, injectOptions))
    .pipe($.inject(injectScripts, injectOptions))
    .pipe($.inject(injectVendor, vendorOptions))
    .pipe($.inject(npmVendors, npmOptions))
    .pipe(gulp.dest(path.join(conf.paths.tmp, '/serve')));
});
```

although it adds the allnode_module files into **.tmp/index.html**   

```
<script src="../node_modules/@uirouter/angularjs/release/ui-router-angularjs.js"></script>
    <script src="../node_modules/angular/index.js"></script>
    <script src="../node_modules/angular-animate/index.js"></script>
```

but when i check this file from page source it open nothing and also display error in console for unexpected Token < . and when click on the index.js it display the  index.js of my project in Application tab ( in devtools)
what is the wrong here?

this is the actual content in **node_modules/angular.index.js**

```
require('./angular');
module.exports = angular;
```

how to fix this issue.

**Comment by cosminlupu** [comment]
Hi there @zymr-keshav, 

This seems to be caused by current working directory used when running the gulp task. The paths returned by the script, will always be relative, so if you've set `nodeModulesPath` to be ` '../node_modules/'` the returned paths for the modules will always start with that.

I'm guessing on your web server setup, when the browser tries to request `../node_modules/angular/index.js`, it is not possible for it to go one folder back and then try the `node_modules` folder.
